services:
  - type: web
    name: log-file-anomaly-explainer
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r Project/requirements.txt
    startCommand: streamlit run Project/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
